### ISSUE TITLE
Bad and incomplete Spanish translation

### ISSUE THREAD

**Issue by BishY1** [TheOnly8Z/ArcCW-Localization#18]
I was looking at the base Spanish translation, it is very poorly done and incomplete, it shows that it used google translator because it has no coherence what, here I made my current and improved version of that translation
[base_es-es.txt](https://github.com/TheOnly8Z/ArcCW-Localization/files/6581087/base_es-es.txt)
GitHub did not allow me to upload the translation in .lua so you can change the file extension
By the way, I don't know how to use extraction requests so I send this translation here

**Comment by TheOnly8Z** [comment]
Hi - another user has contributed some Spanish localization. Can you see if these are better?
